ftd_2018/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('home/')),
    url(r'^home/', include('home.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from . import views

app_name = "home"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^submit_abstract/$', views.submit_abstract, name='submit_abstract'),
    url(r'^submission_success/$', views.submission_success, name='submission_success'),
    url(r'^submission_fail/$', views.submission_fail, name='submission_fail'),
]

home/models.py
from django.db import models


# model for publications
class Abstract(models.Model):
    title = models.CharField(max_length=300)
    abstract_text = models.TextField()
    upload_datetime = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-upload_datetime',)


class Author(models.Model):
    abstract = models.ForeignKey(Abstract, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=300)
    middle_initial = models.CharField(max_length=300, blank=True)
    last_name = models.CharField(max_length=300)
    email = models.EmailField()
    affiliation = models.CharField(max_length=1000)

    def __str__(self):
        return self.first_name + " " + self.last_name

    class Meta:
        ordering = ('last_name',)

home/forms.py
from django import forms
from .models import Abstract, Author


class AbstractForm(forms.ModelForm):
    class Meta:
        model = Abstract
        exclude = ["upload_datetime"]

        labels = {
            'title': 'Abstract title',
            "abstract_text": "Abstract text"
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            "abstract_text": forms.Textarea(
                attrs={'placeholder': 'Abstract body should be limited to 300 words...',
                'class': 'form-control'})
        }


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        exclude = ["abstract"]
        
        labels = {
            'first_name': 'First name',
            "middle_initial": "Middle initial",
            "last_name": "Last name",
            "email": "Email address",
            "affiliation": "Affiliation"
        }
        
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'middle_initial': forms.TextInput(attrs={'placeholder': '(Not required)',
                'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            "affiliation": forms.TextInput(attrs={'class': 'form-control'})
        }

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.core.mail import EmailMessage
from .forms import AbstractForm, AuthorForm

# Create your views here.
def index(request):
    abstract_form = AbstractForm(prefix="abstract_form")
    author_form = AuthorForm(prefix="author_form")
    context_dict = {"abstract_form": abstract_form, "author_form": author_form}
    return render(request, 'home/index.html', context_dict) 


def submit_abstract(request):
    # handle post
    if request.method == "POST":
        abstract_form = AbstractForm(request.POST, prefix="abstract_form")
        author_form = AuthorForm(request.POST, prefix="author_form")

        if abstract_form.is_valid() and author_form.is_valid():
            # form is valid, save to database
            abstract = abstract_form.save(commit=False)

            # word limit
            num_words = len(abstract.abstract_text.split())
            if num_words <= 300:
                abstract.save()
                author = author_form.save(commit=False)
                author.abstract = abstract
                author.save()

                # send confirmation email
                subject = 'SABPA Poster Contest 2018: Abstract Confirmation'
                html_content = "<p>Dear " + author.first_name + "," +\
                    "<p>Congratulations! Your&nbsp;abstract has been successfully submitted " +\
                    "to the 2nd SABPA Life Science and Technology Poster Contest. " +\
                    "Please reply to this email if you need any assistance.</p>" +\
                    "<p>Sincerely,</p><p>SABPA Poster Contest Team</p>"
                from_email = "sabpa.poster@gmail.com"
                to = author.email
                msg = EmailMessage(subject, html_content, from_email, [to])
                msg.content_subtype = "html"
                msg.send()

                return HttpResponseRedirect(reverse('home:submission_success'))

        # word limit failed
        return HttpResponseRedirect(reverse('home:submission_fail'))


def submission_success(request):
    # return html code to tell the user that the submission is successful 
    return render(request, 'home/submission_success.html')

def submission_fail(request):
    # return html code to tell the user that the submission is failed 
    return render(request, 'home/submission_fail.html')

home/templates/home/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="SABPA Life Science and Technology Poster Contest">
    <meta name="author" content="Yuan Tian">

    <link rel="icon" href="{% static 'home/image/sabpa_logo.jpg' %}">

    <title>2nd SABPA Life Science and Technology Poster Contest - Feb 10, 2018 | San Diego, CA</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'home/css/map.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'home/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'home/css/creative.min.css' %}" rel="stylesheet">

    {% block head_block %}
    {% endblock %}

  </head>

  <body id="page-top">
    {% block body_block %}
    {% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'home/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'home/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'home/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'home/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'home/js/creative.min.js' %}"></script>
    <script src="{% static 'home/js/home_ajax.js' %}"></script>

  </body>

</html>

home/templates/home/index.html
{% extends "home/base.html" %}

{% load staticfiles %}

{% block body_block %} 
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">SABPA Poster Contest</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#abstracts">Abstracts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#portfolio">Gallery</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#direction">Direction &amp; Parking</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="masthead text-center text-white d-flex">
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h3>
            8:00 AM to 5:00 PM, Saturday, February 10, 2018
          </h3>
          <h1 class="text-uppercase">
            <strong>2nd SABPA Life Science and Technology Poster Contest</strong>
          </h1>
          <h5 class="section-heading text-white">
            <strong>Hilton San Diego/Del Mar | Del Mar, CA</strong>
          </h5>
          <hr>
        </div>
        <div class="col-lg-8 mx-auto">
          <p class="mb-5">Bridges industry and academia experts to transform therapeutics and diagnositics for patients</p>
          <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
        </div>
      </div>
    </div>
  </header>

  <section class="bg-primary" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <h2 class="section-heading text-white">Innovative Research in Life Science and Technology</h2>
          <hr class="light my-4">
          <p class="text-faded mb-4 lead">To foster a unique opportunity for graduate students, postdoctoral fellows, and junior professionals in life science and technology field, the 2nd SABPA Life Science and Technology Poster Event will be held together with the 2nd SABPA Frontiers in Therapeutics and Diagnostics (FTD) Forum. Please attend this exciting event with your poster, showcase your discovery, exchange innovative ideas, and network with peers and leaders from industry and academia, including investment sector.</p>
          <a class="btn btn-light btn-xl js-scroll-trigger" href="#abstracts">Abstracts</a>
        </div>
      </div>
    </div>
  </section>

  <section id="abstracts">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">Abstracts</h2>
          <hr class="my-4">
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <dl class="row">
            <dt class="col-sm-3">Theme</dt>
            <dd class="col-sm-9">Innovative research in life science and technology</dd>

            <dt class="col-sm-3">Eligibility</dt>
            <dd class="col-sm-9">
              <p>Graduate students and postdoctoral fellows</p>
              <p>Academic and industrial scientists</p>
            </dd>

            <dt class="col-sm-3">Submission</dt>
            <dd class="col-sm-9">Free Submission and  the deadline is <strong>Friday, January 27, 2018 at 11pm</strong> (Space is limited, early submission is strongly recommended)</dd>

            <dt class="col-sm-3">Abstract Instruction</dt>
            <dd class="col-sm-9">
              <p>Presenting author’s name, affiliation, and contact</p>
              <p>Abstract title and body text. Abstract body (&#8828 300 words): can be structured as sections including background, methods and materials, results, discussion and conclusion, and potential implication</p>
            </dd>

            <dt class="col-sm-3">Awards</dt>
            <dd class="col-sm-9">The posters displayed in the event will be evaluated anonymously by a panel of judges, and by all the attendees of FTD forum. Winners will receive the following prizes: First, second and third places and best popularity</dd>

            <dt class="col-sm-3">Other benefits</dt>
            <dd class="col-sm-9">Free admissions of presenting author and one colleague to FTD Forum</dd>

          </dl>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p class="text-center">
            <a class="btn btn-primary btn-lg js-scroll-trigger" href="#submission_form">
              <span class="glyphicon glyphicon-upload"></span>click to submit now!
            </a>
          </p>
          <section class="bg-primary text-white">
            <div class="container">
              <form id="submission_form" action="{% url 'home:submit_abstract' %}" method="post">
                  {% csrf_token %}

                  {% for field in author_form %}
                      <div class="form-group row">
                          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                          <div class="col-sm-10">
                              {{ field }}
                          </div>
                      </div>
                  {% endfor %}

                  {% for field in abstract_form %}
                      <div class="form-group row">
                          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                          <div class="col-sm-10">
                              {{ field }}
                          </div>
                      </div>
                  {% endfor %}

                  <div class="form-group">
                    <div class="offset-sm-2 col-sm-10">
                      <div class="form-check">
                        <label class="form-check-label">
                          <input class="form-check-input" type="checkbox" id="agreeCheck"> Agree to terms:
                        </label>
                        <small id="fileHelp" class="form-text">By submitting an application, you give SABPA the authority to electronically post your abstract, and presentation, and to publish them in printed materials. You are responsible to protect your and not to infringe other’s inventions and intellectual properties. It is also your responsibility for editing your abstract, presentation and providing copy in final, print-ready form.</small>
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="offset-sm-2 col-sm-10">
                      <button type="submit" class="btn btn-dark" id="submitAbstract" disabled>Submit</button>
                    </div>
                  </div>
              </form>
            </div>
          </section>
        </div>
      </div>
    </div>
  </section>

  <section class="p-0" id="portfolio">
    <div class="container-fluid p-0">
      <div class="row no-gutters popup-gallery">
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'home/img/portfolio/fullsize/1.jpg' %}">
            <img class="img-fluid" src="{% static 'home/img/portfolio/thumbnails/1.jpg' %}" alt="">
            <div class="portfolio-box-caption">
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'home/img/portfolio/fullsize/2.jpg' %}">
            <img class="img-fluid" src="{% static 'home/img/portfolio/thumbnails/2.jpg' %}" alt="">
            <div class="portfolio-box-caption">
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'home/img/portfolio/fullsize/3.jpg' %}">
            <img class="img-fluid" src="{% static 'home/img/portfolio/thumbnails/3.jpg' %}" alt="">
            <div class="portfolio-box-caption">
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'home/img/portfolio/fullsize/4.jpg' %}">
            <img class="img-fluid" src="{% static 'home/img/portfolio/thumbnails/4.jpg' %}" alt="">
            <div class="portfolio-box-caption">
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'home/img/portfolio/fullsize/5.jpg' %}">
            <img class="img-fluid" src="{% static 'home/img/portfolio/thumbnails/5.jpg' %}" alt="">
            <div class="portfolio-box-caption">
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'home/img/portfolio/fullsize/6.jpg' %}">
            <img class="img-fluid" src="{% static 'home/img/portfolio/thumbnails/6.jpg' %}" alt="">
            <div class="portfolio-box-caption">
            </div>
          </a>
        </div>
      </div>
    </div>
  </section>

  <section id="direction">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <h2 class="section-heading">Direction &amp; Parking</h2>
          <hr class="my-4">
          <p class="mb-5">Address: 15575 Jimmy Durante Blvd, Del Mar, CA 92014. Parking is free at the hotel.</p>
        </div>
      </div>
    </div>
    <div id="map" class="container google_map">
    </div>
  </section>
  
  <script>
  function initMap() {
    var uluru = {lat: 32.978353, lng: -117.254794};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: uluru
    });
    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCxHgUqQy4zPijq6ZbpWtcLJYbWjL5CqzQ&callback=initMap">
  </script>

  <div id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <h2 class="section-heading">Contact Us</h2>
          <hr class="my-4">
          <p class="mb-5">If you have any questions, please contact us at: </p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8 mx-auto text-center">
          <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
          <p>
            <a href="mailto:ftdposter@sabpa.org">ftdposter@sabpa.org</a>
          </p>
        </div>
      </div>
    </div>
  </div>
  
  <hr>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-center">
          <small class="copyright">Created by <a href="http://www.ytian.me" target="_blank">Yuan Tian</a> with Django.</small>
          <small class="copyright">Copyright &copy; SABPA and Blackrock Digital LLC.</small>
        </div>
      </div>
    </div>
  </footer>

{% endblock %} 

home/templates/home/submission_fail.html
{% extends "home/base.html" %}

{% load staticfiles %}

{% block head_block %}
    <meta http-equiv="refresh" content="5;url={% url 'home:index' %}"/>
{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Submission failed!</h4>
                <p>Please make sure that your abstract text is within the 300-word limit. You will be redirected in 5 seconds... </p>
                <p>Or click <a href="{% url 'home:index' %}"><span style="color:#4169E1">here</span></a> to go back...</p>
        </div>
    </div>
{% endblock %} 

home/templates/home/submission_success.html
{% extends "home/base.html" %}

{% load staticfiles %}

{% block head_block %}
    <meta http-equiv="refresh" content="5;url={% url 'home:index' %}"/>
{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Success!</h4>
                <p>Your abstract has been successfully submitted. A confirmation email will be sent to you shortly. You will be redirected in 5 seconds... </p>
                <p>Or click <a href="{% url 'home:index' %}"><span style="color:#4169E1">here</span></a> to go back...</p>
        </div>
    </div>
{% endblock %} 

home/templates/home/submit_abstract.html
<section class="bg-dark text-white">
    <div class="container">
        <form id="submission_form" action="{% url 'home:submit_abstract' %}" method="post">
            {% csrf_token %}

            {% for field in author_form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}

            {% for field in abstract_form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}

            <div class="form-check">
                <div class="col-sm-10 offset-sm-2">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input">
                        Check me out
                    </label>
                    <small id="fileHelp" class="form-text text-muted">This is some placeholder block-level help text for the above input. It's a bit lighter and easily wraps to a new line.</small>
                </div>
            </div>

            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary" id="submitAbstract">Submit</button>
            </div>
        </form>
    </div>
</section>